# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: job1
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
    
- job: job2
  displayName: Job 2
  steps:
  - script: echo This is script1.job2!
    displayName: 'Script 1 Job 2'

  - script: echo this is script2.job2.
    displayName: 'Script 2 Job 2'